POST https://modulo-ventas.onrender.com/registersell HTTP/1.1
Content-Type: application/json

{
    "id_venta": "5620f1d9-d635-4de3-960a-75e7ef1b9e2a",
    "dni_cliente": "70911900",
    "fecha": "10/27/2023" 
}

###
POST https://modulo-ventas.onrender.com/adddetail HTTP/1.1
Content-Type: application/json

{
    "id_detalle":"05509e04-a7fe-4e18-a72f-25b9b61df45a",
    "id_venta":"5620f1d9-d635-4de3-960a-75e7ef1b9e2a",
    "id_producto":"d7d93988-0514-4302-ae81-64607b0be012",
    "cantidad":1,
    "id_garantia":"0",
    "tipo":"Celular"

}

###
DELETE http://localhost:4000/deletedetail/94c8b396-7389-4e95-8843-b4b5bd319f27 HTTP/1.1

###
GET https://modulo-ventas.onrender.com/getselldni/123456789 HTTP/1.1

###
GET https://modulo-ventas.onrender.com/getlineas/70911900 HTTP/1.1

###
POST https://modulo-ventas.onrender.com/phone HTTP/1.1
Content-Type: application/json

{
    "id_celular": "94c8b396-7389-4e95-8843-b4b5bd319f27",
    "marca": "Samsung",
    "modelo": "S23 Ultra",
    "precio": 5099.00,
    "color": "Negro",
    "almacenamiento": 512,
    "idgarantia": 0
}

###
PUT http://localhost:4000/pagolinea/912117920 HTTP/1.1

###
PUT http://localhost:4000/atrasolinea/912117920 HTTP/1.1

###
PUT http://localhost:4000/cancelarlinea/912117920 HTTP/1.1

###
GET http://localhost:4000/searchbilldni/70911900 HTTP/1.1