POST https://modulo-ventas.onrender.com/registersell HTTP/1.1
Content-Type: application/json

{
    "id_venta": "5620f1d9-d635-4de3-960a-75e7ef1b9e2a",
    "dni_cliente": "70911900",
    "fecha": "10/27/2023" 
}

###
PUT https://modulo-ventas.onrender.com/reactivarlinea/912572342 HTTP/1.1

###
GET http://localhost:4000/createreport HTTP/1.1
Content-Type: application/json

{
    "tipo":"General",
    "tiempo":"Mes",
    "periodo1":"2023-11-20",
    "periodo2":"2023-11-24"
}

###
GET https://modulo-ventas.onrender.com/createereportweekly HTTP/1.1
Content-Type: application/json

{
    "periodo1":"2023-10-20",
    "periodo2":"2023-12-24"
}

###
POST https://modulo-ventas.onrender.com/adddetail HTTP/1.1
Content-Type: application/json

{
    "id_detalle":"0a360e7e-d930-44e6-a436-b6ebc1e4284f",
    "id_venta":"5620f1d9-d635-4de3-960a-75e7ef1b9e2a",
    "id_producto":"34567891",
    "cantidad":1,
    "id_garantia":"0",
    "tipo":"Celular"

}

###
DELETE http://localhost:4000/deletedetail/94c8b396-7389-4e95-8843-b4b5bd319f27 HTTP/1.1

###
GET https://modulo-ventas.onrender.com/getselldni/123456789 HTTP/1.1


###
GET https://modulo-ventas.onrender.com/searchwarranty/1 HTTP/1.1

###
GET https://clientemodulocrm.onrender.com/buscarPorDNI/123456789 HTTP/1.1


###
GET https://modulo-ventas.onrender.com/getlineas/70911900 HTTP/1.1

###
PUT https://modulo-ventas.onrender.com/paybill/5b40d888-1d87-4b83-9568-d4f4d573ceeb HTTP/1.1

###
GET https://clientemodulocrm.onrender.com/buscarPorDNI/123456789 HTTP/1.1

###
POST https://modulo-ventas.onrender.com/phone HTTP/1.1
Content-Type: application/json

{
    "id_celular": "94c8b396-7389-4e95-8843-b4b5bd319f27",
    "marca": "Samsung",
    "modelo": "S23 Ultra",
    "precio": 5099.00,
    "color": "Negro",
    "almacenamiento": 512,
    "idgarantia": 0
}

###
PUT http://localhost:4000/pagolinea/912117920 HTTP/1.1

###
PUT http://localhost:4000/atrasolinea/912117920 HTTP/1.1

###
PUT http://localhost:4000/cancelarlinea/912117920 HTTP/1.1

###
GET http://localhost:4000/searchbilldni/70911900 HTTP/1.1